apiVersion: batch/v1
kind: Job
metadata:
  name: a-job-failing
spec:
  template:
    spec:
      containers:
      - name: a-job-failing
        image: bash
        command: ["bash", "-c", "sleep 1; exit 1" ]
      restartPolicy: Never
  backoffLimit: 3
