apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
spec:
  template:
    spec:
      containers:
      - name: a-job
        image: bash
        command: ["bash", "-c", "sleep 1; exit 0" ]
      restartPolicy: Never
