apiVersion: batch/v1
kind: Job
metadata:
  name: a-job
spec:
  template:
    spec:
      containers:
      - name: a-job
        image: bash
        command: ["bash", "-c", "sleep $((RANDOM/1024+1)); exit $((RANDOM/16384))" ]
      restartPolicy: Never
  parallelism: 4
