apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      volumes:
      - name: passwords-volume
        secret:
          secretName: passwords
      containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: passwords-volume
          mountPath: /etc/passwords
