apiVersion: v1
kind: ConfigMap
metadata:
  name: values
data:
  cpu: "4000"
  memory: "17179869184"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        resources:
          requests:
            cpu: "500m"
            memory: "500Mi"
          limits:
            cpu: "1"
            memory: "1Gi"
        volumeMounts:
        - name: config
          mountPath: /config
          readOnly: true
      volumes:
      - name: config
        projected:
          sources:
          - configMap:
              name: values
              items:
              - key: cpu
                path: cpu/value
              - key: memory
                path: memory/value
          - downwardAPI:
              items:
              - path: cpu/limits
                resourceFieldRef:
                  resource: limits.cpu
                  divisor: "0.001"
                  containerName: nginx
              - path: memory/limits
                resourceFieldRef:
                  resource: limits.memory
                  containerName: nginx
              - path: cpu/requests
                resourceFieldRef:
                  resource: requests.cpu
                  divisor: "0.001"
                  containerName: nginx
              - path: memory/requests
                resourceFieldRef:
                  resource: requests.memory
                  containerName: nginx
